version: '3'

services:
  sftp-ssh:
    build:
      context: .
      dockerfile: ./conf/sftp/Dockerfile
    image: sftp-pgbackrest:${TAG}
    container_name: sftp
    hostname: sftp
    command: /home/pgbackrest/sftp_prepare.sh
    volumes:
      - "backrest_data_sftp-ssh:/var/lib/pgbackrest"
    environment:
      - "BACKREST_UID"
      - "BACKREST_GID"
      - "BACKREST_TLS_SERVER=disable"
    expose:
      - "2222"
    networks:
      - ssh

  sftp-tls :
    build:
      context: .
      dockerfile: ./conf/sftp/Dockerfile
    image: sftp-pgbackrest:${TAG}
    container_name: sftp
    hostname: sftp
    command: /home/pgbackrest/sftp_prepare.sh
    volumes:
      - "backrest_data_sftp-tls:/var/lib/pgbackrest"
    environment:
      - "BACKREST_UID"
      - "BACKREST_GID"
      - "BACKREST_TLS_SERVER=disable"
    expose:
      - "2222"
    networks:
      - tls

networks:
  ssh:
  tls:

volumes:
  backrest_data_sftp-ssh:
  backrest_data_sftp-tls: