version: '3'

services:
  pg-ssh:
    build:
      context: .
      dockerfile: ./conf/pg/Dockerfile
      args:
        CONTAINER_TYPE: ssh
    image: pg-pgbackrest:${TAG}
    container_name: pg-ssh
    hostname: pg-ssh
    command: /var/lib/postgresql/pg_prepare.sh
    environment:
      - "BACKREST_UID"
      - "BACKREST_GID"
    expose:
      - "2222"
    depends_on:
      - minio
      - nginx
      - createbucket
    networks:
      - ssh

  pg-tls:
    build:
      context: .
      dockerfile: ./conf/pg/Dockerfile
      args:
        CONTAINER_TYPE: tls
    image: pg-pgbackrest:${TAG}
    container_name: pg-tls
    hostname: pg-tls
    command: /var/lib/postgresql/pg_prepare.sh
    environment:
      - "BACKREST_UID"
      - "BACKREST_GID"
      - "BACKREST_HOST_TYPE=tls"
    expose:
      - "8432"
    depends_on:
      - minio
      - nginx
      - createbucket
    networks:
      - tls

networks:
  ssh:
  tls: