name: build

on: [push, pull_request]

jobs:
  build_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pgbackrest_version: ["2.31", "2.32", "2.33", "2.34", "2.35"]
    env: 
      latest_version: "2.35"
      pgbackrest_completion_version: "v0.3"
      build_platforms: "linux/amd64,linux/arm64"
    steps:
    - uses: actions/checkout@v2

    - name: Get repo tag
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      id: vars
      run: |
        echo ::set-output name=repo_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Build pgbackrest images
      run: |
        docker buildx build \
          -f Dockerfile \
          --platform ${BUILD_PLATFORMS} \
          --build-arg BACKREST_VERSION=${TAG} \
          --build-arg REPO_BUILD_TAG=${REPO_TAG} \
          --build-arg BACKREST_COMPLETION_VERSION=${COMPL_TAG} \
          -t pgbackrest:${TAG} .
      env: 
        TAG: ${{ matrix.pgbackrest_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}
        COMPL_TAG: ${{ env.pgbackrest_completion_version }}
        BUILD_PLATFORMS: ${{ env.build_platforms }}

    - name: Build and push tag image to ghcr.io and Docker Hub
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        echo ${GITHUB_PKG} | docker login ghcr.io -u ${GITHUB_USER} --password-stdin
        echo ${DOCKERHUB_PKG} | docker login -u ${DOCKERHUB_USER} --password-stdin
        docker buildx build --push \
            -f Dockerfile \
            --platform ${BUILD_PLATFORMS} \
            --build-arg BACKREST_VERSION=${TAG} \
            --build-arg REPO_BUILD_TAG=${REPO_TAG} \
            --build-arg BACKREST_COMPLETION_VERSION=${COMPL_TAG} \
            -t ghcr.io/${GITHUB_USER}/pgbackrest:${TAG} \
            -t ghcr.io/${GITHUB_USER}/pgbackrest:${TAG}-${REPO_TAG} \
            -t ${DOCKERHUB_USER}/pgbackrest:${TAG} \
            -t ${DOCKERHUB_USER}/pgbackrest:${TAG}-${REPO_TAG} .
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_PKG: ${{ secrets.GUTHUB_CR_PAT }}
        DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
        DOCKERHUB_PKG: ${{ secrets.DOCKEHUB_TOKEN }}
        TAG: ${{ matrix.pgbackrest_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}
        COMPL_TAG: ${{ env.pgbackrest_completion_version }}
        BUILD_PLATFORMS: ${{ env.build_platforms }}


    - name: Build and push tag (latest) image to ghcr.io and Docker Hub
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && matrix.pgbackrest_version == env.latest_version
      run: |
        echo ${GITHUB_PKG} | docker login ghcr.io -u ${GITHUB_USER} --password-stdin
        echo ${DOCKERHUB_PKG} | docker login -u ${DOCKERHUB_USER} --password-stdin
        docker buildx build --push \
            -f Dockerfile \
            --platform ${BUILD_PLATFORMS} \
            --build-arg BACKREST_VERSION=${TAG} \
            --build-arg REPO_BUILD_TAG=${REPO_TAG} \
            --build-arg BACKREST_COMPLETION_VERSION=${COMPL_TAG} \
            -t ghcr.io/${GITHUB_USER}/pgbackrest:latest \
            -t ${DOCKERHUB_USER}/pgbackrest:latest .
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_PKG: ${{ secrets.GUTHUB_CR_PAT }}
        DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
        DOCKERHUB_PKG: ${{ secrets.DOCKEHUB_TOKEN }}
        TAG: ${{ matrix.pgbackrest_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}
        COMPL_TAG: ${{ env.pgbackrest_completion_version }}
        BUILD_PLATFORMS: ${{ env.build_platforms }}
